### ISSUE TITLE
规则匹配

### ISSUE THREAD

**Issue by tinybobo** [Thesharing/LFESM#1]
作者您好~感谢您的分享，想问下legal feature attributes规则匹配的代码或者思路可以分享下嘛，谢谢~
bitdongbo@163.com

**Comment by Thesharing** [comment]
Hello, @tinybobo! Thank you for your comments. The codes about attributes locate at https://github.com/Thesharing/LFESM/blob/master/models/feature.py, please feel free to ask questions if you have any.
