### ISSUE TITLE
代码运行方式和结果询问

### ISSUE THREAD

**Issue by stack-heap-overflow** [Thesharing/LFESM#2]
作者你好，感谢对论文代码的开源。我尝试复现你的工作，修改少量代码(文件路径，ground_truth预处理，一些device的bug，关闭fp16)后可以运行训练，但训练中发现准确率只有不到50%，猜测有可能是我在数据预处理或者pytorch版本设置上和预期不一致。请问能否公布详细的代码运行流程便于进行复现，谢谢！

**Comment by Thesharing** [comment]
> 作者你好，感谢对论文代码的开源。我尝试复现你的工作，修改少量代码(文件路径，ground_truth预处理，一些device的bug，关闭fp16)后可以运行训练，但训练中发现准确率只有不到50%，猜测有可能是我在数据预处理或者pytorch版本设置上和预期不一致。请问能否公布详细的代码运行流程便于进行复现，谢谢！

十分感谢对我们工作的关注。

主要关注以下几个点：
1. 训练参数是否一致
2. 预训练模型是否一致，我们用的是[OpenCLaP](https://github.com/thunlp/OpenCLaP)
3. 是否应用了数据增广
4. NVIDIA Apex能够降低内存占用，同时加快训练速度，建议开启
5. 我们当时训练时使用的CUDA为10.2，PyTorch版本为1.4.0
